CREATE OR REPLACE TABLE USUARIO(
  ID_USUARIO INT NOT NULL AUTO_INCREMENT,
  DELETADO BOOLEAN NOT NULL,
  PERFIL CHAR NOT NULL,
  NOME VARCHAR2(70) NOT NULL,
  EMAIL VARCHAR2(70) NOT NULL,
  DATA_NASC DATETIME NOT NULL,
  LOCALIZACAO BOOLEAN NOT NULL,
  NOTIFICACAO BOOLEAN NOT NULL,
  PRIMARY KEY (ID_USUARIO)
);
